const API_URL = window.APP_CONFIG.API_URL;
const tokenKey = 'animal_hospital_anomaly_token';
const loginView = document.querySelector('#login-view');
const profileView = document.querySelector('#profile-view');
const startPanel = document.querySelector('#game-start');
const hud = document.querySelector('#game-hud');
const message = document.querySelector('#message');
let state = null;
let currentPatient = null;
let verified = false;
let caseTimer = null;
let caseSeconds = 20;
let generalSeconds = 300;
let generalTimer = null;
let treatmentPatientId = null;
let treatmentHealth = 100;
let inspectionCaseId = null;
const patientImages = { Luna: ['assets/luna-normal.jpg', 'assets/luna-anomalia.jpg'], Max: ['assets/max-normal.jpg', 'assets/luna-anomalia.jpg'], Nala: ['assets/max-normal.jpg', 'assets/luna-anomalia.jpg'], Coco: ['assets/kira-normal.jpg', 'assets/coco-anomalia.jpg'], Milo: ['assets/max-normal.jpg', 'assets/milo-anomalia.jpg'], Kira: ['assets/kira-normal.jpg', 'assets/coco-anomalia.jpg'] };

function showMessage(text, success = false) { message.textContent = text || ''; message.className = success ? 'success' : ''; }
window.addEventListener('error', (event) => showMessage(`Error de interfaz: ${event.message || 'revisa la consola'}`));
function showLogin() { loginView.hidden = false; profileView.hidden = true; loginView.style.display = 'grid'; profileView.style.display = 'none'; }
function showProfile(email) { document.querySelector('#welcome-message').textContent = email; loginView.hidden = true; profileView.hidden = false; loginView.style.display = 'none'; profileView.style.display = 'flex'; }
function api(path, options = {}) { return fetch(`${API_URL}${path}`, { ...options, headers: { Authorization: `Bearer ${localStorage.getItem(tokenKey)}`, ...(options.headers || {}) } }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || 'La operación no pudo completarse.'); return data; }); }
function patientKey(patient) { return String(patient?.nombre || 'Luna').split(' ')[0]; }
function imageFor(patient, anomaly = false) { const pair = patientImages[patientKey(patient)] || patientImages.Luna; return anomaly ? pair[1] : pair[0]; }
function stopCaseTimer() { if (caseTimer) clearInterval(caseTimer); caseTimer = null; }
function startCaseTimer() { stopCaseTimer(); caseSeconds = 60; updateCaseTimer(); caseTimer = setInterval(() => { caseSeconds -= 1; updateCaseTimer(); if (caseSeconds <= 0) { stopCaseTimer(); showMessage('El minuto de inspección terminó. La decisión sigue siendo tuya; revisa la evidencia y decide.'); } }, 1000); }
function updateCaseTimer() { const el = document.querySelector('#case-timer'); if (el) el.textContent = `00:${String(Math.max(0, caseSeconds)).padStart(2, '0')}`; }
function stopGeneralTimer() { if (generalTimer) clearInterval(generalTimer); generalTimer = null; }
function updateGeneralTimer() { const el = document.querySelector('#general-timer'); if (el) el.textContent = `${String(Math.floor(generalSeconds / 60)).padStart(2, '0')}:${String(generalSeconds % 60).padStart(2, '0')}`; }
function startGeneralTimer() { if (generalTimer) return; updateGeneralTimer(); generalTimer = setInterval(() => { generalSeconds -= 1; updateGeneralTimer(); if (generalSeconds <= 0) { stopGeneralTimer(); api('/partida/finalizar', { method: 'POST' }).then((result) => finishReport(result.reporte, 'El tiempo general de cinco minutos terminó.')).catch((error) => showMessage(error.message)); } }, 1000); }

function installGameUi() {
  profileView.classList.add('rebuild-mode');
  if (!document.querySelector('#tutorial-overlay')) {
    profileView.insertAdjacentHTML('beforeend', `<div id="tutorial-overlay" class="tutorial-overlay" hidden><div class="tutorial-card"><span class="eyebrow">MANUAL DE RECEPCIÓN</span><h2 id="tutorial-title">Cómo jugar</h2><div id="tutorial-body"></div><div class="tutorial-med-guide"><b>Guía rápida de curación</b><span>💊 Analgésico · dolor e inflamación</span><span>🧪 Antibiótico · fiebre y infección</span><span>💧 Suero · deshidratación y debilidad</span><span>🧴 Antiparasitario · parásitos y picazón</span><span>💉 Sedante · ansiedad y agitación</span></div><p id="tutorial-error" class="tutorial-error" role="alert"></p><div class="tutorial-footer"><span id="tutorial-step">1 / 6</span><button id="tutorial-next" class="primary-button" type="button">Siguiente <span>→</span></button></div></div></div>`);
  }
  document.querySelector('#special-room')?.remove(); document.querySelector('.lower-grid')?.remove(); document.querySelector('.events-panel')?.remove();
  document.querySelector('#reception-scene').innerHTML = `<div class="desk-board"><div class="desk-status"><span>RECEPCIÓN ANIMAL // CASO ACTIVO</span><b></b></div><div class="desk-window"><div class="window-label">VENTANILLA DE INGRESO <i>● LIVE</i></div><div id="photo-reception" class="photo-screen"><p>Esperando visitante...</p></div><div id="photo-verification" class="photo-screen verification-screen" hidden></div></div><div class="desk-left"><button class="hotspot hotspot-bell" data-evidence="today" type="button" title="Lista de visitantes">●</button><span class="desk-note">VISITANTES<br>DE HOY</span><button class="hotspot hotspot-alert" data-evidence="checklist" type="button" title="Checklist">!</button></div><div class="desk-folders"><button data-evidence="archive" data-floor="1" type="button">1.º PISO</button><button data-evidence="archive" data-floor="2" type="button">2.º PISO</button><button data-evidence="archive" data-floor="3" type="button">3.º PISO</button></div><div class="desk-bottom"><button class="desk-object phone-object" data-evidence="phone" type="button" title="Teléfono">☎<small>TELÉFONO</small></button><button class="desk-object mic-object" id="ask-visitor-v2" type="button" disabled title="Interrogar">◉<small>INTERROGAR</small></button><button class="desk-object camera-object" id="scan-patient" type="button" title="Tomar fotografía">◌<small>FOTO</small></button><div class="paper-stack"><button data-evidence="id" type="button">IDENTIFICACIÓN</button><button data-evidence="request" type="button">SOLICITUD</button></div><div class="desk-actions"><button id="reject-patient" class="decision-reject" type="button" disabled>✕ BLOQUEAR</button><button id="confirm-patient" class="decision-accept" type="button" disabled>✓ ADMITIR</button></div></div><div class="visitor-caption"><span id="visitor-dialogue">La persona espera detrás de la ventanilla.</span><b id="report-data"><span>Sin visitante</span></b></div></div><div id="evidence-modal" class="evidence-modal" hidden><div class="evidence-modal-card"><header><b id="evidence-title">DOCUMENTO</b><button id="close-evidence" type="button">×</button></header><div id="evidence-content"></div></div></div>`;
  document.querySelector('#treatment-scene').innerHTML = `<div class="v2-scene-label"><span>SALA DE TRATAMIENTO // CAMILLA</span><b>CASO ADMITIDO</b></div><div class="treatment-v2"><section class="treatment-patient-card"><div id="treatment-avatar" class="treatment-avatar"></div><h2 id="treatment-name">Paciente</h2><p id="treatment-symptoms">Revisa los síntomas del caso.</p><div class="health-label"><span>ESTADO DEL PACIENTE</span><b id="patient-health">100%</b></div><div class="health-track"><div id="patient-health-bar"></div></div></section><aside class="treatment-options"><h3>Herramientas disponibles</h3><p>Deduce el tratamiento a partir de los síntomas.</p><div id="treatment-options-grid"></div><button id="apply-treatment" class="decision-accept" type="button" disabled>Aplicar herramienta</button><button id="leave-treatment" class="secondary-button" type="button">Salir del caso</button></aside></div>`;
  document.querySelector('#scan-patient').addEventListener('click', scanCurrent); document.querySelector('#zoom-patient')?.addEventListener('click', () => document.querySelector('#photo-verification')?.classList.toggle('zoomed')); document.querySelector('#ask-visitor-v2').addEventListener('click', askVisitor); document.querySelector('#confirm-patient').addEventListener('click', admitCurrent); document.querySelector('#reject-patient').addEventListener('click', () => rejectCurrent(false)); const evidenceModal = document.querySelector('#evidence-modal'); const closeEvidence = () => { evidenceModal.hidden = true; }; document.querySelector('#close-evidence').addEventListener('click', closeEvidence); evidenceModal.addEventListener('click', (event) => { if (event.target === evidenceModal) closeEvidence(); }); document.querySelectorAll('[data-evidence]').forEach((button) => button.addEventListener('click', () => openEvidence(button.dataset.evidence, button.dataset.floor))); document.querySelector('#apply-treatment').addEventListener('click', applyTreatment); document.querySelector('#leave-treatment').addEventListener('click', () => { showMessage('Caso abandonado. El paciente queda sin resolver.'); showReception(); });
  document.querySelectorAll('.desk-folders button').forEach((button) => button.addEventListener('click', () => { const floor = Number(button.dataset.floor); const roster = currentPatient?.inspection?.archivos_por_piso?.[floor]; if (roster) currentPatient.inspection.archivo = roster; }, true));
  document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !evidenceModal.hidden) closeEvidence(); });
}
function renderPhoto(target, patient, anomaly = false, label = '') { const element = document.querySelector(target); if (!element) return; element.innerHTML = `<div class="photo-frame"><img src="${imageFor(patient, anomaly)}" alt="${patient.nombre}" /></div><strong>${patient.nombre}</strong><small>${label}</small>`; }
function renderReception(data) { const incoming = data.paciente_actual; if (!incoming) { currentPatient = null; inspectionCaseId = null; stopCaseTimer(); renderPhoto('#photo-reception', { nombre: 'Sin visitante' }, false, 'La ventanilla está libre'); document.querySelector('#report-data').innerHTML = '<b>Sin visitante</b><span>Espera el siguiente caso.</span>'; return; } if (!currentPatient || (!verified && inspectionCaseId !== Number(incoming.id))) { currentPatient = incoming; inspectionCaseId = Number(incoming.id); } if (!verified) startCaseTimer(); renderPhoto('#photo-reception', currentPatient, false, 'Observación directa'); const report = currentPatient.inspection?.archivo || {}; document.querySelector('#report-data').innerHTML = `<b>Ficha de referencia · AH-${String(currentPatient.id).padStart(4, '0')}</b><span>Nombre registrado: ${report.nombre || currentPatient.nombre}</span><span>Ubicación: piso ${report.piso ?? '-'} · apartamento ${report.apartamento ?? '-'}</span><span>Especie: ${report.especie || 'Paciente animal registrado'}</span>`; document.querySelector('#scan-patient').disabled = Boolean(currentPatient.detectado); document.querySelector('#zoom-patient')?.toggleAttribute('disabled', !verified); document.querySelector('#ask-visitor-v2').disabled = !verified; document.querySelector('#confirm-patient').disabled = !verified; document.querySelector('#reject-patient').disabled = !verified; hud.hidden = false; startPanel.hidden = true; }
function updateStats(game) { const values = { 'turn-number': game.turno_actual, coins: game.monedas, sanity: `${game.cordura}/100`, level: game.nivel, 'game-status': game.estado }; Object.entries(values).forEach(([id, value]) => { const el = document.querySelector(`#${id}`); if (el) el.textContent = value; }); }
function unlockCaseControls(hasPatient = Boolean(currentPatient)) { ['scan-patient', 'ask-visitor-v2', 'confirm-patient', 'reject-patient'].forEach((id) => { const control = document.querySelector(`#${id}`); if (control) control.disabled = !hasPatient; }); }
async function refreshGame() { const data = await api('/partida/estado'); state = data; updateStats(data.partida); renderReception(data); document.querySelector('.desk-board')?.classList.remove('curtain-closing', 'curtain-opening'); unlockCaseControls(Boolean(data.paciente_actual)); }
async function scanCurrent() { if (!currentPatient || inspectionCaseId !== Number(currentPatient.id)) return; const caseId = Number(currentPatient.id); try { const data = await api('/partida/accion/escanear-paciente', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pacienteId: caseId }) }); const scanned = data.paciente; if (Number(scanned.id) !== caseId) throw new Error('La captura no corresponde al visitante actual. Inténtalo nuevamente.'); currentPatient = { ...currentPatient, ...scanned, nombre: currentPatient.nombre }; verified = true; const verification = document.querySelector('#photo-verification'); verification.hidden = false; renderPhoto('#photo-verification', currentPatient, Boolean(scanned.es_anomalia), 'Captura de verificación del mismo caso'); document.querySelector('#visitor-dialogue').textContent = 'El visitante declara: «Vengo por una revisión veterinaria. Mi registro debería estar en sus archivos».'; renderReception({ ...state, paciente_actual: currentPatient }); unlockCaseControls(true); showMessage('Fotografía tomada. Compara ambos paneles y los documentos.', true); } catch (error) { showMessage(error.message); } }
function askVisitor() { const lines = ['«Me llamo como aparece en la ficha; vine por una revisión».', '«El motivo de mi visita está en la solicitud».', '«Puede consultar el archivo antes de dejarme pasar».', '«No recuerdo todos los detalles, pero mi expediente debería ayudar».']; document.querySelector('#visitor-dialogue').textContent = `El visitante responde: ${lines[Math.floor(Math.random() * lines.length)]}`; }
function openEvidence(kind, floor = '') { if (!currentPatient) return; const i = currentPatient.inspection || {}; const archive = i.archivo || {}; const id = i.identificacion || {}; const request = i.solicitud || {}; const content = { id: `<div class="paper"><b>DOCUMENTO DE IDENTIDAD</b><span>${id.nombre}</span><span>Piso ${id.piso} · Apartamento ${id.apartamento}</span><span>Válido hasta: ${id.vencimiento}</span><small>Compara estos datos con los otros documentos y la fotografía.</small></div>`, request: `<div class="paper"><b>SOLICITUD DE ENTRADA</b><span>Solicitante: ${request.nombre}</span><span>Piso ${request.piso} · Apartamento ${request.apartamento}</span><span>Motivo declarado: ${request.motivo}</span></div>`, archive: `<div class="paper"><b>ARCHIVO OFICIAL · ${floor ? `${floor}.º PISO` : 'PISO DEL PACIENTE'}</b><span>${archive.nombre}</span><span>Ubicación: piso ${archive.piso} · apartamento ${archive.apartamento}</span><span>Registro permanente del hospital.</span></div>`, today: '<div class="paper"><b>LISTA DE HOY</b><span>Luna · Max · Nala</span><span>Coco · Milo · Kira</span><small>Es una referencia; no confirma por sí sola la identidad.</small></div>', phone: `<div class="paper phone-panel"><b>TELÉFONO DE SEGURIDAD</b><span>Marca el apartamento ${id.apartamento} para confirmar quién vive allí.</span><button id="call-evidence" class="secondary-button" type="button">Marcar número</button><small id="call-result">La línea aún no se ha conectado.</small></div>`, checklist: '<div class="paper checklist"><label><input type="checkbox"> Nombre comparado</label><label><input type="checkbox"> Foto comparada</label><label><input type="checkbox"> Piso comprobado</label><label><input type="checkbox"> Declaración revisada</label><small>El checklist es una nota personal, no una respuesta automática.</small></div>' }[kind] || ''; document.querySelector('#evidence-title').textContent = kind.toUpperCase(); document.querySelector('#evidence-content').innerHTML = content; document.querySelector('#evidence-modal').hidden = false; document.querySelector('#call-evidence')?.addEventListener('click', () => { document.querySelector('#call-result').textContent = 'La línea responde: «El residente confirma que revises su identificación antes de dejarlo pasar». '; }); }
function openEvidence(kind, floor = '') { if (!currentPatient) return; const i = currentPatient.inspection || {}; const id = i.identificacion || {}; const request = i.solicitud || {}; const claimedFloor = Number(id.piso || i.archivo?.piso || 1); const names = { 1: 'Max', 2: 'Coco', 3: 'Kira' }; const records = { 1: { nombre: names[1], piso: 1, apartamento: 101 }, 2: { nombre: names[2], piso: 2, apartamento: 102 }, 3: { nombre: names[3], piso: 3, apartamento: 103 } }; if (!currentPatient.es_anomalia) records[claimedFloor] = { nombre: currentPatient.nombre, piso: claimedFloor, apartamento: Number(id.apartamento || 100) }; const archive = records[Number(floor)] || records[claimedFloor]; const content = { id: `<div class="paper"><b>DOCUMENTO DE IDENTIDAD</b><span>${id.nombre || currentPatient.nombre}</span><span>Piso ${id.piso} · Apartamento ${id.apartamento}</span><span>Válido hasta: ${id.vencimiento || '24/09/2026'}</span><small>Compara estos datos con los demás documentos.</small></div>`, request: `<div class="paper"><b>SOLICITUD DE ENTRADA</b><span>Solicitante: ${request.nombre || currentPatient.nombre}</span><span>Piso ${request.piso} · Apartamento ${request.apartamento}</span><span>Motivo: ${request.motivo || 'revisión veterinaria'}</span></div>`, archive: `<div class="paper"><b>ARCHIVO OFICIAL · ${archive.piso}.º PISO</b><span>${archive.nombre}</span><span>Ubicación: piso ${archive.piso} · apartamento ${archive.apartamento}</span><small>Este registro pertenece únicamente a este piso.</small></div>`, today: '<div class="paper"><b>LISTA DE HOY</b><span>Luna · Max · Nala</span><span>Coco · Milo · Kira</span><small>La lista no reemplaza la comparación de documentos.</small></div>', phone: `<div class="paper phone-panel"><b>TELÉFONO DE SEGURIDAD</b><span>Llama al apartamento ${id.apartamento || '-'}</span><button id="call-evidence" class="secondary-button" type="button">Marcar número</button><small id="call-result">La llamada aún no se ha realizado.</small></div>`, checklist: '<div class="paper checklist"><label><input type="checkbox"> Identificación comparada</label><label><input type="checkbox"> Solicitud comparada</label><label><input type="checkbox"> Archivo del piso revisado</label><label><input type="checkbox"> Fotografía tomada</label><small>Cuando termines, cierra esta ventana y decide BLOQUEAR o ADMITIR.</small></div>' }[kind] || ''; document.querySelector('#evidence-title').textContent = kind.toUpperCase(); document.querySelector('#evidence-content').innerHTML = content; document.querySelector('#evidence-modal').hidden = false; document.querySelector('#call-evidence')?.addEventListener('click', () => { document.querySelector('#call-result').textContent = 'La línea responde con información parcial. Úsala como pista.'; }); }
document.addEventListener('click', (event) => { if (event.target?.id !== 'call-evidence' || !currentPatient) return; const id = currentPatient.inspection?.identificacion || {}; const floor = Number(id.piso || 1); const result = document.querySelector('#call-result'); if (!result) return; result.textContent = currentPatient.es_anomalia ? `El residente confirma el apartamento ${id.apartamento || '-'} del piso ${floor}, pero no reconoce a ${currentPatient.nombre}.` : `El residente confirma que ${currentPatient.nombre} vive en el piso ${floor}, apartamento ${id.apartamento || '-'}.`; });
document.addEventListener('click', (event) => { const button = event.target?.closest?.('[data-evidence="id"],[data-evidence="request"]'); if (!button || !currentPatient) return; setTimeout(() => { const code = currentPatient.inspection?.identificacion?.codigo || `AH-${String(currentPatient.id).padStart(4, '0')}`; const content = document.querySelector('#evidence-content'); if (!content || content.querySelector('.case-code')) return; const line = document.createElement('span'); line.className = 'case-code'; line.textContent = `Código de caso: ${code}`; content.querySelector('.paper')?.insertBefore(line, content.querySelector('.paper small')); }, 0); });
document.addEventListener('click', (event) => { const button = event.target?.closest?.('[data-evidence="id"],[data-evidence="request"]'); if (!button || !currentPatient) return; setTimeout(() => { const paper = document.querySelector('#evidence-content .paper'); if (!paper || paper.querySelector('.document-detail')) return; const detail = document.createElement('span'); detail.className = 'document-detail'; if (button.dataset.evidence === 'id') detail.textContent = `Especie: paciente animal registrado · Señas: ${currentPatient.es_anomalia ? 'alteración visual detectada' : 'sin anomalías visibles'}`; else detail.textContent = 'Horario de visita: turno actual · Contacto: central veterinaria · Motivo declarado: revisión veterinaria'; paper.insertBefore(detail, paper.querySelector('small')); }, 0); });
document.addEventListener('click', (event) => { const button = event.target?.closest?.('[data-evidence="id"],[data-evidence="request"]'); if (!button || !currentPatient) return; setTimeout(() => { const paper = document.querySelector('#evidence-content .paper'); const id = currentPatient.inspection?.identificacion || {}; const request = currentPatient.inspection?.solicitud || {}; if (!paper) return; const parts = String(currentPatient.nombre || 'Paciente').split(' '); const first = parts.shift(); const last = parts.join(' ') || 'Registrado'; const code = id.codigo || `AH-${String(currentPatient.id).padStart(4, '0')}`; if (button.dataset.evidence === 'id') { paper.innerHTML = `<b>DOCUMENTO DE IDENTIDAD</b><strong class="document-name">${first} ${last}</strong><span>N.º de identificación: ${code}</span><span>Especie: paciente animal registrado</span><span>Fecha de registro: 03/1980</span><span>Piso declarado: ${id.piso} · Apartamento ${id.apartamento}</span><small>Compara la fotografía y la información con la solicitud.</small>`; } else { paper.innerHTML = `<b>SOLICITUD DE INGRESO</b><span>Nombre: ${first}</span><span>Apellido: ${last}</span><span>Apartamento: P0${request.piso}-${String(request.apartamento).slice(-2)}</span><span>Motivo:</span><strong class="request-reason">Soy residente del edificio. Mi apartamento es el ${String(request.apartamento).slice(-2)} del piso ${request.piso}.</strong><span>Código de caso: ${code}</span>`; } }, 0); });
document.addEventListener('click', (event) => { if (event.target?.id !== 'scan-patient' || !verified) return; const verification = document.querySelector('#photo-verification'); if (!verification) return; verification.hidden = !verification.hidden; event.preventDefault(); event.stopImmediatePropagation(); }, true);
async function admitCurrent() { try { const result = await api('/partida/accion/admitir-paciente', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pacienteId: currentPatient.id }) }); stopCaseTimer(); if (result.game_over) return finishReport(result.reporte, 'La cordura llegó a cero.'); if (!result.correcto) { showMessage('La decisión provocó una alerta grave. Revisa la evidencia con más cuidado.'); await refreshGame(); return; } showTreatment(currentPatient); showMessage('Paciente admitido. Pasa a la camilla y deduce su tratamiento.', true); } catch (error) { showMessage(error.message); } }
async function rejectCurrent() { if (!currentPatient) return; try { const result = await api('/partida/accion/rechazar-paciente', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pacienteId: currentPatient.id }) }); stopCaseTimer(); verified = false; const verification = document.querySelector('#photo-verification'); if (verification) { verification.hidden = true; verification.innerHTML = ''; } const board = document.querySelector('.desk-board'); board?.classList.add('curtain-closing'); const receptionPhoto = document.querySelector('#photo-reception'); if (receptionPhoto) receptionPhoto.innerHTML = '<p>La cortina se cierra…</p>'; await new Promise((resolve) => setTimeout(resolve, 450)); if (result.game_over) return finishReport(result.reporte, 'La cordura llegó a cero.'); board?.classList.remove('curtain-closing'); board?.classList.add('curtain-opening'); await new Promise((resolve) => setTimeout(resolve, 450)); board?.classList.remove('curtain-opening'); showMessage(result.correcto ? 'La puerta se abre. Siguiente paciente.' : 'La puerta se abre para el siguiente caso, pero este quedó como error.', result.correcto); await refreshGame(); } catch (error) { showMessage(error.message); } }
function showTreatment(patient) { treatmentPatientId = patient.id; treatmentHealth = 100; document.querySelector('#reception-scene').hidden = true; document.querySelector('#treatment-scene').hidden = false; document.querySelector('#treatment-avatar').innerHTML = `<img src="${imageFor(patient, false)}" alt="${patient.nombre}">`; document.querySelector('#treatment-name').textContent = patient.nombre; document.querySelector('#treatment-symptoms').textContent = `Síntomas observados: ${patient.condicion || 'observa su estado y declaración'}`; const options = [['analgesico', '💊 Analgésico'], ['antibiotico', '🧪 Antibiótico'], ['suero', '💧 Suero'], ['antiparasitario', '🧴 Antiparasitario'], ['sedante', '💉 Sedante'], ['observacion', '🔍 Observación']]; document.querySelector('#treatment-options-grid').innerHTML = options.map(([value, label]) => `<label class="treatment-choice"><input type="radio" name="treatment-choice" value="${value}"><span>${label}</span></label>`).join(''); document.querySelector('#apply-treatment').disabled = false; updateHealth(); }
function updateHealth() { document.querySelector('#patient-health').textContent = `${treatmentHealth}%`; document.querySelector('#patient-health-bar').style.width = `${treatmentHealth}%`; document.querySelector('#patient-health-bar').classList.toggle('low', treatmentHealth <= 35); }
async function applyTreatment() { const selected = document.querySelector('input[name="treatment-choice"]:checked')?.value; if (!selected) return showMessage('Selecciona una herramienta de tratamiento.'); try { const result = await api('/partida/accion/aplicar-tratamiento', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pacienteId: treatmentPatientId, medicamentosSeleccionados: [selected] }) }); treatmentHealth = result.salud_paciente; updateHealth(); if (result.game_over) return finishReport(result.reporte, 'El caso se perdió y la partida terminó.'); if (!result.correcto) { showMessage('El estado del paciente empeora. Revisa los síntomas y prueba otra herramienta.'); return; } showMessage('El paciente se estabilizó. Caso resuelto.', true); verified = false; showReception(); } catch (error) { showMessage(error.message); } }
function showReception() { document.querySelector('#treatment-scene').hidden = true; document.querySelector('#reception-scene').hidden = false; const verification = document.querySelector('#photo-verification'); if (verification) { verification.hidden = true; verification.innerHTML = ''; } const receptionPhoto = document.querySelector('#photo-reception'); if (receptionPhoto) receptionPhoto.innerHTML = '<p>Esperando visitante...</p>'; const modal = document.querySelector('#evidence-modal'); if (modal) modal.hidden = true; verified = false; inspectionCaseId = null; treatmentPatientId = null; refreshGame().catch((error) => showMessage(error.message)); }
function finishReport(report, text) { stopCaseTimer(); stopGeneralTimer(); hud.hidden = true; startPanel.hidden = false; document.querySelector('#game-over-screen').hidden = false; document.querySelector('#game-over-message').textContent = text; if (report) { document.querySelector('#final-report').hidden = false; document.querySelector('#report-content').innerHTML = `<p>Turno alcanzado: <b>${report.turno_alcanzado}</b></p><p>Pacientes curados: <b>${report.pacientes_curados}</b></p><p>Errores: <b>${report.errores_cometidos}</b></p><p>Monedas: <b>${report.monedas_ganadas}</b></p>`; } }
document.querySelector('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 8000); try { showMessage('Conectando con el servidor…'); const response = await fetch(`${API_URL}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), password: form.get('password') }), signal: controller.signal }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No fue posible iniciar sesión.'); localStorage.setItem(tokenKey, data.token); await loadProfile(data.token); } catch (error) { showMessage(error.name === 'AbortError' ? 'El servidor no responde. Verifica que MySQL y el backend estén encendidos.' : error.message); } finally { clearTimeout(timeout); } });
async function loadProfile(token) { const response = await fetch(`${API_URL}/auth/me`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No fue posible validar la sesión.'); showProfile(data.user.email); installGameUi(); document.querySelector('#game-start').hidden = false; document.querySelector('#game-hud').hidden = true; }
const tutorialPages = [
  ['La recepción', 'Observa al animal que aparece en la ventanilla. Todo ocurre en esta misma pantalla: no necesitas desplazarte.'],
  ['Revisa sus documentos', 'Pulsa IDENTIFICACIÓN y SOLICITUD. Abre la carpeta del piso correspondiente y compara nombre, código, apartamento y características.'],
  ['Comprueba la lista', 'La hoja de VISITANTES DE HOY te dice quién esperaba venir. Si no aparece o algo no coincide, investiga antes de decidir.'],
  ['Interroga y llama', 'Pulsa el micrófono para interrogar. Usa el teléfono para confirmar el apartamento. Las respuestas son pistas, no la solución automática.'],
  ['Decide', 'BLOQUEAR llama a seguridad y ADMITIR deja pasar al paciente. Tú decides si coincide; el sistema valida tu decisión.'],
  ['Cura al paciente', 'Después de ADMITIR, pasa a la sala de tratamiento. Lee los síntomas, elige el medicamento correcto y aplícalo para completar el caso.']
];
function showTutorial() { const overlay = document.querySelector('#tutorial-overlay'); let step = 0; const title = document.querySelector('#tutorial-title'); const body = document.querySelector('#tutorial-body'); const label = document.querySelector('#tutorial-step'); const next = document.querySelector('#tutorial-next'); const tutorialError = document.querySelector('#tutorial-error'); if (tutorialError) tutorialError.textContent = ''; const paint = () => { title.textContent = tutorialPages[step][0]; body.textContent = tutorialPages[step][1]; label.textContent = `${step + 1} / ${tutorialPages.length}`; next.innerHTML = step === tutorialPages.length - 1 ? 'Comenzar <span>→</span>' : 'Siguiente <span>→</span>'; }; next.onclick = () => { if (step < tutorialPages.length - 1) { step += 1; paint(); } else { beginGame(overlay); } }; overlay.hidden = false; paint(); }
async function beginGame(overlay = document.querySelector('#tutorial-overlay')) { const tutorialError = document.querySelector('#tutorial-error'); try { if (tutorialError) tutorialError.textContent = 'Iniciando partida…'; document.querySelector('#game-over-screen').hidden = true; document.querySelector('#final-report').hidden = true; document.querySelector('#treatment-scene').hidden = true; document.querySelector('#reception-scene').hidden = false; stopGeneralTimer(); generalSeconds = 300; await api('/partida/iniciar', { method: 'POST' }); verified = false; await refreshGame(); document.querySelector('.desk-board')?.classList.remove('curtain-closing', 'curtain-opening'); overlay.hidden = true; startGeneralTimer(); showMessage('Partida iniciada. Tienes cinco minutos para recibir, investigar y curar pacientes.', true); } catch (error) { const text = `No se pudo iniciar la partida: ${error.message}`; if (tutorialError) tutorialError.textContent = text; showMessage(text); overlay.hidden = false; } }
document.querySelector('#start-game-button').addEventListener('click', showTutorial);
document.querySelector('#logout-button').addEventListener('click', () => { localStorage.removeItem(tokenKey); showLogin(); });
document.querySelector('#finish-game').addEventListener('click', async () => { try { const result = await api('/partida/finalizar', { method: 'POST' }); stopGeneralTimer(); finishReport(result.reporte, 'Partida finalizada por el operador.'); } catch (error) { showMessage(error.message); } });
document.querySelector('#open-lobby').addEventListener('click', () => { hud.hidden = true; startPanel.hidden = false; stopCaseTimer(); });
function setupRegistration() { const form = document.querySelector('#login-form'); if (!form || document.querySelector('#register-toggle')) return; form.insertAdjacentHTML('afterbegin', '<button id="register-toggle" class="register-toggle" type="button">Crear cuenta</button><div id="register-panel" class="register-panel" hidden><label for="register-email">Correo nuevo</label><input id="register-email" type="email" placeholder="correo@hospital.com" autocomplete="email"><label for="register-password">Contraseña</label><input id="register-password" type="password" minlength="8" placeholder="Mínimo 8 caracteres" autocomplete="new-password"><label for="register-password-confirm">Repetir contraseña</label><input id="register-password-confirm" type="password" minlength="8" placeholder="Repite la contraseña" autocomplete="new-password"><button id="register-submit" class="primary-button" type="button">Crear cuenta <span>→</span></button><p id="register-message" class="register-message" role="alert"></p></div>'); const toggle = document.querySelector('#register-toggle'); const panel = document.querySelector('#register-panel'); const messageEl = document.querySelector('#register-message'); toggle.addEventListener('click', () => { panel.hidden = !panel.hidden; messageEl.textContent = ''; if (!panel.hidden) document.querySelector('#register-email').focus(); }); document.querySelector('#register-submit').addEventListener('click', async () => { const email = document.querySelector('#register-email').value.trim(); const password = document.querySelector('#register-password').value; const confirmation = document.querySelector('#register-password-confirm').value; if (!email || !password || password.length < 8) { messageEl.textContent = 'Completa un correo válido y una contraseña de mínimo 8 caracteres.'; return; } if (password !== confirmation) { messageEl.textContent = 'Las contraseñas no coinciden.'; return; } const button = document.querySelector('#register-submit'); button.disabled = true; messageEl.textContent = 'Creando cuenta…'; try { const response = await fetch(`${API_URL}/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo crear la cuenta.'); messageEl.className = 'register-message created'; messageEl.textContent = 'Cuenta creada correctamente. Ya puedes iniciar sesión.'; form.querySelector('#email').value = email; form.querySelector('#password').value = ''; setTimeout(() => { panel.hidden = true; messageEl.className = 'register-message'; messageEl.textContent = ''; form.querySelector('#password').focus(); }, 1400); } catch (error) { messageEl.className = 'register-message'; messageEl.textContent = error.message; } finally { button.disabled = false; } }); }
setupRegistration();
async function boot() { const token = localStorage.getItem(tokenKey); if (!token) return showLogin(); try { await fetch(`${API_URL}/partida/abandonar`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); } catch (_error) { /* si el backend no responde, igualmente se limpia la sesión local */ } finally { localStorage.removeItem(tokenKey); stopGeneralTimer(); stopCaseTimer(); showLogin(); } }
boot();
